"""CSV and JSON output adapter for deal-reconstruction audits.

This module is intentionally limited to presentation and persistence.

It does not:

- access Bitget or any other exchange;
- normalize raw fills;
- reconstruct deals;
- read lifecycle state;
- change orders, positions, TP or SL;
- import live-trading or reconciliation modules.
"""

from __future__ import annotations

import json
from collections import Counter
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import pandas as pd

from hf_audit.deal_reconstruction.domain.enums import FillOrigin
from hf_audit.deal_reconstruction.domain.models import Deal, PositionState
from hf_audit.deal_reconstruction.domain.reconstruction import (
    DealReconstructionResult,
    ReconstructionAnomaly,
)
from hf_audit.deal_reconstruction.ports.reporting import (
    ReconstructionReportWriter,
)


ZERO = Decimal("0")

MANUAL_ORIGINS = frozenset(
    {
        FillOrigin.IOS,
        FillOrigin.WEB,
        FillOrigin.ANDROID,
    }
)


@dataclass(frozen=True, slots=True)
class ReconstructionReportPaths:
    """Strongly typed paths generated by the reporting adapter."""

    deals: Path
    manual_close_deals: Path
    open_positions: Path
    anomalies: Path
    summary_by_asset: Path
    summary: Path

    def as_mapping(self) -> Mapping[str, Path]:
        return {
            "deals": self.deals,
            "manual_close_deals": self.manual_close_deals,
            "open_positions": self.open_positions,
            "anomalies": self.anomalies,
            "summary_by_asset": self.summary_by_asset,
            "summary": self.summary,
        }


def decimal_sum(values: Iterable[Decimal]) -> Decimal:
    """Return an exact Decimal sum."""

    return sum(values, ZERO)


def unique_origin_values(
    origins: Iterable[FillOrigin],
) -> tuple[str, ...]:
    """Return stable origin values without duplicates."""

    return tuple(
        dict.fromkeys(
            origin.value
            for origin in origins
        )
    )


def deal_to_row(deal: Deal) -> dict[str, object]:
    """Map one completed domain deal to a flat report row."""

    entry_trade_ids = tuple(
        fill.trade_id
        for fill in deal.entry_leg.fills
    )
    exit_trade_ids = tuple(
        fill.trade_id
        for fill in deal.exit_leg.fills
    )
    entry_order_ids = tuple(
        dict.fromkeys(
            fill.order_id
            for fill in deal.entry_leg.fills
        )
    )
    exit_order_ids = tuple(
        dict.fromkeys(
            fill.order_id
            for fill in deal.exit_leg.fills
        )
    )
    exit_origins = unique_origin_values(
        fill.origin
        for fill in deal.exit_leg.fills
    )

    return {
        "deal_id": deal.deal_id,
        "exchange": deal.exchange,
        "symbol": deal.symbol,
        "position_side": deal.position_side.value,
        "opened_at": deal.opened_at.isoformat(),
        "closed_at": deal.closed_at.isoformat(),
        "duration_seconds": deal.duration_seconds,
        "quantity": str(deal.quantity),
        "entry_fill_count": len(
            deal.entry_leg.fills
        ),
        "exit_fill_count": len(
            deal.exit_leg.fills
        ),
        "entry_vwap": str(
            deal.entry_leg.vwap
        ),
        "exit_vwap": str(
            deal.exit_leg.vwap
        ),
        "entry_fees": str(
            deal.entry_leg.fees
        ),
        "exit_fees": str(
            deal.exit_leg.fees
        ),
        "total_fees": str(
            deal.total_fees
        ),
        "exchange_realised_pnl": str(
            deal.exchange_realised_pnl
        ),
        "net_realised_pnl": str(
            deal.net_realised_pnl
        ),
        "close_reason": (
            deal.close_reason.value
        ),
        "includes_manual_close": bool(
            deal.includes_manual_close
        ),
        "origins": ",".join(
            unique_origin_values(
                deal.origins
            )
        ),
        "exit_origins": ",".join(
            exit_origins
        ),
        "entry_trade_ids": ",".join(
            entry_trade_ids
        ),
        "exit_trade_ids": ",".join(
            exit_trade_ids
        ),
        "entry_order_ids": ",".join(
            entry_order_ids
        ),
        "exit_order_ids": ",".join(
            exit_order_ids
        ),
    }


def open_position_to_row(
    position: PositionState,
) -> dict[str, object]:
    """Map an end-of-data open position to a report row."""

    entry_quantity = decimal_sum(
        fill.quantity
        for fill in position.entry_fills
    )
    exit_quantity = decimal_sum(
        fill.quantity
        for fill in position.exit_fills
    )
    entry_fees = decimal_sum(
        fill.fee
        for fill in position.entry_fills
    )
    exit_fees = decimal_sum(
        fill.fee
        for fill in position.exit_fills
    )
    realised_pnl_to_date = decimal_sum(
        fill.realised_pnl
        for fill in position.exit_fills
    )

    manual_exit_fill_count = sum(
        1
        for fill in position.exit_fills
        if fill.origin in MANUAL_ORIGINS
    )

    return {
        "exchange": position.exchange,
        "symbol": position.symbol,
        "position_side": (
            position.position_side.value
        ),
        "opened_at": (
            position.opened_at.isoformat()
        ),
        "entry_quantity": str(
            entry_quantity
        ),
        "exit_quantity": str(
            exit_quantity
        ),
        "open_quantity": str(
            position.open_quantity
        ),
        "quantity_balance": str(
            entry_quantity
            - exit_quantity
            - position.open_quantity
        ),
        "entry_fill_count": len(
            position.entry_fills
        ),
        "exit_fill_count": len(
            position.exit_fills
        ),
        "entry_fees": str(
            entry_fees
        ),
        "exit_fees": str(
            exit_fees
        ),
        "fees_to_date": str(
            entry_fees + exit_fees
        ),
        "realised_pnl_to_date": str(
            realised_pnl_to_date
        ),
        "manual_exit_fill_count": (
            manual_exit_fill_count
        ),
        "origins": ",".join(
            unique_origin_values(
                position.origins
            )
        ),
        "entry_trade_ids": ",".join(
            fill.trade_id
            for fill in position.entry_fills
        ),
        "exit_trade_ids": ",".join(
            fill.trade_id
            for fill in position.exit_fills
        ),
    }


def anomaly_to_row(
    anomaly: ReconstructionAnomaly,
) -> dict[str, object]:
    """Map one reconstruction anomaly to a flat report row."""

    return {
        "anomaly_type": (
            anomaly.anomaly_type
        ),
        "symbol": anomaly.symbol,
        "position_side": (
            anomaly.position_side.value
        ),
        "trade_id": anomaly.trade_id,
        "timestamp": (
            anomaly.timestamp_iso
        ),
        "quantity": str(
            anomaly.quantity
        ),
        "message": anomaly.message,
    }


def build_deal_frame(
    deals: Sequence[Deal],
) -> pd.DataFrame:
    """Create the completed-deal report frame."""

    columns = [
        "deal_id",
        "exchange",
        "symbol",
        "position_side",
        "opened_at",
        "closed_at",
        "duration_seconds",
        "quantity",
        "entry_fill_count",
        "exit_fill_count",
        "entry_vwap",
        "exit_vwap",
        "entry_fees",
        "exit_fees",
        "total_fees",
        "exchange_realised_pnl",
        "net_realised_pnl",
        "close_reason",
        "includes_manual_close",
        "origins",
        "exit_origins",
        "entry_trade_ids",
        "exit_trade_ids",
        "entry_order_ids",
        "exit_order_ids",
    ]

    return pd.DataFrame(
        [
            deal_to_row(deal)
            for deal in deals
        ],
        columns=columns,
    )


def build_manual_close_deal_frame(
    deals: Sequence[Deal],
) -> pd.DataFrame:
    """Create a report containing only deals with manual close fills."""

    return build_deal_frame(
        [
            deal
            for deal in deals
            if deal.includes_manual_close
        ]
    )


def build_open_position_frame(
    positions: Sequence[PositionState],
) -> pd.DataFrame:
    """Create the end-of-data open-position report frame."""

    columns = [
        "exchange",
        "symbol",
        "position_side",
        "opened_at",
        "entry_quantity",
        "exit_quantity",
        "open_quantity",
        "quantity_balance",
        "entry_fill_count",
        "exit_fill_count",
        "entry_fees",
        "exit_fees",
        "fees_to_date",
        "realised_pnl_to_date",
        "manual_exit_fill_count",
        "origins",
        "entry_trade_ids",
        "exit_trade_ids",
    ]

    return pd.DataFrame(
        [
            open_position_to_row(position)
            for position in positions
        ],
        columns=columns,
    )


def build_anomaly_frame(
    anomalies: Sequence[ReconstructionAnomaly],
) -> pd.DataFrame:
    """Create the reconstruction-anomaly report frame."""

    columns = [
        "anomaly_type",
        "symbol",
        "position_side",
        "trade_id",
        "timestamp",
        "quantity",
        "message",
    ]

    return pd.DataFrame(
        [
            anomaly_to_row(anomaly)
            for anomaly in anomalies
        ],
        columns=columns,
    )


def build_asset_summary_frame(
    result: DealReconstructionResult,
) -> pd.DataFrame:
    """Aggregate completed deals, open positions and anomalies by asset."""

    symbols = sorted(
        {
            deal.symbol
            for deal in result.deals
        }
        |
        {
            position.symbol
            for position in result.open_positions
        }
        |
        {
            anomaly.symbol
            for anomaly in result.anomalies
        }
    )

    rows: list[dict[str, object]] = []

    for symbol in symbols:
        symbol_deals = [
            deal
            for deal in result.deals
            if deal.symbol == symbol
        ]
        symbol_positions = [
            position
            for position in result.open_positions
            if position.symbol == symbol
        ]
        symbol_anomalies = [
            anomaly
            for anomaly in result.anomalies
            if anomaly.symbol == symbol
        ]

        rows.append(
            {
                "symbol": symbol,
                "completed_deal_count": len(
                    symbol_deals
                ),
                "manual_close_deal_count": sum(
                    1
                    for deal in symbol_deals
                    if deal.includes_manual_close
                ),
                "open_position_count": len(
                    symbol_positions
                ),
                "anomaly_count": len(
                    symbol_anomalies
                ),
                "exchange_realised_pnl": str(
                    decimal_sum(
                        deal.exchange_realised_pnl
                        for deal in symbol_deals
                    )
                ),
                "total_fees": str(
                    decimal_sum(
                        deal.total_fees
                        for deal in symbol_deals
                    )
                ),
                "net_realised_pnl": str(
                    decimal_sum(
                        deal.net_realised_pnl
                        for deal in symbol_deals
                    )
                ),
                "open_quantity": str(
                    decimal_sum(
                        position.open_quantity
                        for position in symbol_positions
                    )
                ),
                "manual_open_position_count": sum(
                    1
                    for position in symbol_positions
                    if any(
                        origin in MANUAL_ORIGINS
                        for origin in position.origins
                    )
                ),
            }
        )

    columns = [
        "symbol",
        "completed_deal_count",
        "manual_close_deal_count",
        "open_position_count",
        "anomaly_count",
        "exchange_realised_pnl",
        "total_fees",
        "net_realised_pnl",
        "open_quantity",
        "manual_open_position_count",
    ]

    return pd.DataFrame(
        rows,
        columns=columns,
    )


def build_summary(
    *,
    result: DealReconstructionResult,
    context: Mapping[str, object] | None = None,
) -> dict[str, object]:
    """Build the JSON-compatible executive reconstruction summary."""

    context_data = dict(
        context or {}
    )

    anomaly_counts = Counter(
        anomaly.anomaly_type
        for anomaly in result.anomalies
    )

    completed_realised_pnl = decimal_sum(
        deal.exchange_realised_pnl
        for deal in result.deals
    )
    completed_fees = decimal_sum(
        deal.total_fees
        for deal in result.deals
    )
    completed_net_pnl = decimal_sum(
        deal.net_realised_pnl
        for deal in result.deals
    )

    completed_quantity_balanced = all(
        deal.entry_leg.quantity
        == deal.exit_leg.quantity
        for deal in result.deals
    )

    open_position_balanced = all(
        (
            decimal_sum(
                fill.quantity
                for fill in position.entry_fills
            )
            - decimal_sum(
                fill.quantity
                for fill in position.exit_fills
            )
        )
        == position.open_quantity
        for position in result.open_positions
    )

    checks = {
        "processed_fill_count_non_negative": (
            result.processed_fill_count >= 0
        ),
        "completed_deal_count_consistent": (
            result.completed_deal_count
            == len(result.deals)
        ),
        "open_position_count_consistent": (
            result.open_position_count
            == len(result.open_positions)
        ),
        "anomaly_count_consistent": (
            result.anomaly_count
            == len(result.anomalies)
        ),
        "completed_deal_quantities_balanced": (
            completed_quantity_balanced
        ),
        "open_position_quantities_balanced": (
            open_position_balanced
        ),
        "completed_deal_quantities_positive": all(
            deal.quantity > ZERO
            for deal in result.deals
        ),
        "open_position_quantities_positive": all(
            position.open_quantity > ZERO
            for position in result.open_positions
        ),
    }

    return {
        "status": (
            "PASS"
            if all(checks.values())
            else "FAIL"
        ),
        "processed_fill_count": (
            result.processed_fill_count
        ),
        "completed_deal_count": (
            result.completed_deal_count
        ),
        "manual_close_deal_count": sum(
            1
            for deal in result.deals
            if deal.includes_manual_close
        ),
        "open_position_count": (
            result.open_position_count
        ),
        "anomaly_count": (
            result.anomaly_count
        ),
        "anomaly_counts": dict(
            sorted(
                anomaly_counts.items()
            )
        ),
        "completed_exchange_realised_pnl": str(
            completed_realised_pnl
        ),
        "completed_total_fees": str(
            completed_fees
        ),
        "completed_net_realised_pnl": str(
            completed_net_pnl
        ),
        "checks": checks,
        "context": context_data,
    }


@dataclass(frozen=True, slots=True)
class CsvJsonReconstructionReportWriter(
    ReconstructionReportWriter
):
    """Persist reconstruction reports using CSV and JSON formats."""

    csv_encoding: str = "utf-8"
    json_encoding: str = "utf-8"

    def write(
        self,
        *,
        result: DealReconstructionResult,
        output_dir: Path,
        context: Mapping[str, object] | None = None,
    ) -> Mapping[str, Path]:
        """Write all reconstruction reports atomically by file."""

        output_dir = Path(
            output_dir
        )
        output_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        paths = ReconstructionReportPaths(
            deals=(
                output_dir
                / "reconstructed_deals.csv"
            ),
            manual_close_deals=(
                output_dir
                / "reconstructed_manual_close_deals.csv"
            ),
            open_positions=(
                output_dir
                / "reconstructed_open_positions.csv"
            ),
            anomalies=(
                output_dir
                / "reconstruction_anomalies.csv"
            ),
            summary_by_asset=(
                output_dir
                / "reconstruction_summary_by_asset.csv"
            ),
            summary=(
                output_dir
                / "reconstruction_summary.json"
            ),
        )

        deal_frame = build_deal_frame(
            result.deals
        )
        manual_deal_frame = (
            build_manual_close_deal_frame(
                result.deals
            )
        )
        open_position_frame = (
            build_open_position_frame(
                result.open_positions
            )
        )
        anomaly_frame = build_anomaly_frame(
            result.anomalies
        )
        asset_summary_frame = (
            build_asset_summary_frame(
                result
            )
        )
        summary = build_summary(
            result=result,
            context=context,
        )

        deal_frame.to_csv(
            paths.deals,
            index=False,
            encoding=self.csv_encoding,
        )
        manual_deal_frame.to_csv(
            paths.manual_close_deals,
            index=False,
            encoding=self.csv_encoding,
        )
        open_position_frame.to_csv(
            paths.open_positions,
            index=False,
            encoding=self.csv_encoding,
        )
        anomaly_frame.to_csv(
            paths.anomalies,
            index=False,
            encoding=self.csv_encoding,
        )
        asset_summary_frame.to_csv(
            paths.summary_by_asset,
            index=False,
            encoding=self.csv_encoding,
        )
        paths.summary.write_text(
            json.dumps(
                summary,
                indent=2,
                sort_keys=True,
                default=str,
            ),
            encoding=self.json_encoding,
        )

        return paths.as_mapping()
